#!/bin/bash
cd /app
if ! [ -f "artisan" ]
then
   echo "Creating new Project.\n\n"
   composer create-project laravel/laravel project $1
   shopt -s dotglob
   mv project/* .
   rm -rf project
else
   echo "Project already exists. F*ck off!"
fi