#!/bin/bash
cd /var/www/html

if ! [ -n "${SKIP_COMPOSER}" ]
then
   composer install
fi


if ! [ -n "${SKIP_MIGRATIONS}" ]
then
    php artisan migrate
fi

if ! [ -n "${SKIP_SEEDERS}" ]
then
    php artisan db:seed
fi

if [ -n "${STORAGE_LINK}" ]
then
    php artisan storage:link
fi

httpd -D FOREGROUND