#!/bin/bash
cd /app

if ! [ -n "${SKIP_COMPOSER}" ]
then
    composer install
fi

if ! [ -n "${SKIP_MIGRATIONS}" ]
then
    php artisan migrate
fi

if ! [ -n "${SKIP_SEEDERS}" ]
then
    php artisan db:seed
fi

if [ -n "${STORAGE_LINK}" ]
then
    php artisan storage:link
fi

if [ -n .env ]
then
   cp .env.example .env
   php artisan key:generate
fi

echo "Starting Laravel Dev Environment"
php artisan serve --host=0.0.0.0 --port=8000
