#!/bin/bash
cd /app

echo "Installing composer packages"
composer install 


if ! [ -n "${SKIP_MIGRATIONS}" ]
then
    php artisan migrate
fi

if ! [ -n "${SKIP_SEEDERS}" ]
then
    php artisan db:seed
fi


echo "Starting Laravel Dev Environment"
php artisan serve --host=0.0.0.0 --port=8000