#!/bin/bash
cd /app

echo "Installing composer packages"
composer install 
echo "Running migrations"
php artisan migrate
echo "Starting Laravel Dev Environment"
php artisan serve --host=0.0.0.0 --port=8000