name: "Docker Build"
description: "Build Docker containers"
inputs:
  build_context:
    required: true 
    description: "The build context path"
  build_tags:
    required: true 
    description: "The build tags"
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.build_context }}
        tags: ${{ inputs.build_tags }}
        push: true