name: "Docker Build"
description: "Build Docker containers"
inputs:
  build_context:
    required: true 
    description: "The build context path"
  build_tags:
    required: true 
    description: "The build tags"
  dockerhub_user:
    required: true
    description: "Dockerhub username"
  dockerhub_password:
    required: true
    description: "Dockerhub password"
  dockerfile:
    required: true 
    description: Dockerfile for building
    default: Dockerfile
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_user }}
        password: ${{ inputs.dockerhub_password }}
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build image and push to Docker Hub
      run: docker build ${{ input.build_context }} ${{ inputs.build_tags }} -f ${{ input.dockerfile }}
      shell: bash
    - name: Push 
      run: docker push ${{ inputs.build_tags }}
      shell: bash
     