name: Build PHP 
on: 
  workflow_call: 
    inputs:
      version:
        required: true 
        description: "The PHP Version"
        type: string
    secrets:
      dockerhub_user:
        required: true
        description: "Dockerhub username"
      dockerhub_password:
        required: true
        description: "Dockerhub password"
jobs: 
  Base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ["","Xdebug"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.dockerhub_user }}
          dockerhub_password: ${{ secrets.dockerhub_password }}
          build_context: ./PHP/Base
          build_dockerfile: ${context}/Dockerfile${{ matrix.dockerfile }}
          build_tags: |
            ggmartinez/php:${{ inputs.version }}${{ matrix.dockerfile }}
          build_args: |
            PHP_VERSION=${{ inputs.version }}
