name: 'Dockerfiles buld'

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  # =================
  # Terraform
  # =================

  Terraform-123:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Terraform
          build_tags: |
            ggmartinez/terraform:1.2.3
            ggmartinez/terraform:latest

  # =================
  # AWS CLI
  # =================

  AWS-CLI-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./AWS/CLIv2
          build_tags: |
            ggmartinez/awscli:2
            ggmartinez/awscli:latest

  # =================
  # PHP
  # =================

  PHP:
    strategy:
      matrix:
        version: [74, 80, 81, 82]
    uses: ggmartinez/dockerfiles/.github/workflows/build-php.yml@main
    secrets:
      dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
    with:
      version: ${{ matrix.version }}

  





  # =================
  # Python 
  # =================

  Python2-Debugpy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Python/2/Debugpy
          build_tags: |
            ggmartinez/python:2-debugpy
  Python3-Debugpy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Python/3/Debugpy
          build_tags: |
            ggmartinez/python:3-debugpy
  Django-165:
    runs-on: ubuntu-latest
    needs: Python2-Debugpy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Python/Django/1.6.5
          build_tags: |
            ggmartinez/django:1.6.5


