name: 'PHP 8 - Full'

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  Terraform-123:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Terraform
          build_tags: |
            ggmartinez/terraform:1.2.3
            ggmartinez/terraform:latest

  PHP8-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/8/
          build_tags: |
            ggmartinez/php:8
            ggmartinez/php:latest
  PHP8-Xdebug:
    needs: PHP8-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: "Dockerfile-Xdebug"
          build_context: ./PHP/8
          build_tags: |
            ggmartinez/php:8-xdebug
  PHP8-Apache:
    needs: PHP8-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: Dockerfile-apache
          build_context: ./PHP/8
          build_tags: |
            ggmartinez/php:8-apache
            ggmartinez/php:latest-apache
  PHP8-Apache-Xdebug:
    needs: PHP8-Apache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: "Dockerfile-Xdebug-apache"
          build_context: ./PHP/8
          build_tags: |
            ggmartinez/php:8-apache-xdebug

  PHP7-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/8/
          build_tags: |
            ggmartinez/php:7
  PHP7-Xdebug:
    needs: PHP7-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: "Dockerfile-Xdebug"
          build_context: ./PHP/8
          build_tags: |
            ggmartinez/php:7-xdebug
  PHP7-Apache:
    needs: PHP7-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: Dockerfile-apache
          build_context: ./PHP/7
          build_tags: |
            ggmartinez/php:7-apache
  PHP7-Apache-Xdebug:
    needs: PHP7-Apache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: "Dockerfile-Xdebug-apache"
          build_context: ./PHP/7
          build_tags: |
            ggmartinez/php:7-apache-xdebug

  Laravel9-PHP7:
    runs-on: ubuntu-latest
    needs: PHP7-Base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel9
          dockerfile: "Dockerfile-php7"
          build_tags: |
            ggmartinez/php:laravel9-php7
  Laravel9-PHP7-Xdebug:
    needs: Laravel9-PHP7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: "Dockerfile-php7-Xdebug"
          build_context: ./PHP8/Laravel9
          build_tags: |
            ggmartinez/laravel9-php7-xdebug



  Laravel9-PHP8:
    runs-on: ubuntu-latest
    needs: PHP8-Base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel9
          dockerfile: "Dockerfile-php8"
          build_tags: |
            ggmartinez/php:laravel9-php8
  Laravel9-PHP8-Xdebug:
    needs: Laravel9-PHP8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: "Dockerfile-php8-Xdebug"
          build_context: ./PHP8/Laravel9
          build_tags: |
            ggmartinez/laravel9-php8-xdebug


