name: 'Dockerfiles buld'

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  Terraform-123:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Terraform
          build_tags: |
            ggmartinez/terraform:1.2.3
            ggmartinez/terraform:latest

  PHP7-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/7/Base
          build_tags: |
            ggmartinez/php:7
  PHP7-Xdebug:
    needs: PHP7-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/7/Xdebug
          build_tags: |
            ggmartinez/php:7-xdebug
  PHP7-Apache:
    needs: PHP7-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/7/Apache
          build_tags: |
            ggmartinez/php:7-apache
  PHP7-Apache-Xdebug:
    needs: PHP7-Apache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/7/Apache-Xdebug
          build_tags: |
            ggmartinez/php:7-apache-xdebug

