name: 'Dockerfiles buld'

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  # =================
  # Terraform
  # =================

  Terraform-123:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Terraform
          build_tags: |
            ggmartinez/terraform:1.2.3
            ggmartinez/terraform:latest

  # =================
  # AWS CLI
  # =================

  AWS-CLI-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./AWS/CLIv2
          build_tags: |
            ggmartinez/awscli:2
            ggmartinez/awscli:latest

  # =================
  # PHP 7
  # =================

  PHP7-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/7/Base
          build_tags: |
            ggmartinez/php:7
  PHP7-Xdebug:
    needs: PHP7-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/7/Xdebug
          build_tags: |
            ggmartinez/php:7-Xdebug
  PHP7-Apache:
    needs: PHP7-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/7/Apache
          build_tags: |
            ggmartinez/php:7-apache
  PHP7-Apache-Xdebug:
    needs: PHP7-Apache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/7/Apache-Xdebug
          build_tags: |
            ggmartinez/php:7-apache-Xdebug

  # =================
  # PHP 8
  # =================

  PHP8-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/8/Base
          build_tags: |
            ggmartinez/php:8
  PHP8-Xdebug:
    needs: PHP8-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/8/Xdebug
          build_tags: |
            ggmartinez/php:8-Xdebug
  PHP8-Apache:
    needs: PHP8-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/8/Apache
          build_tags: |
            ggmartinez/php:8-apache
  PHP8-Apache-Xdebug:
    needs: PHP8-Apache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/8/Apache-Xdebug
          build_tags: |
            ggmartinez/php:8-apache-Xdebug


  # =================
  # Laravel 8 - PHP 7
  # =================

  Laravel8-PHP7:
    runs-on: ubuntu-latest
    needs: PHP7-Base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel/8/php7
          build_tags: |
            ggmartinez/laravel:8-php7
  Laravel8-PHP7-Xdebug:
    needs: Laravel8-PHP7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel/8/php7-xdebug
          build_tags: |
            ggmartinez/laravel:8-php7-Xdebug
  Laravel8-PHP7-MSSQL:
    needs: Laravel8-PHP7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel/8/php7-mssql
          build_tags: |
            ggmartinez/laravel:8-php7-mssql
  Laravel8-PHP7-MSSQL-Xdebug:
    needs: Laravel8-PHP7-Xdebug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel/8/php7-mssql-xdebug
          build_tags: |
            ggmartinez/laravel:8-php7-Xdebug-mssql

  # =================
  # Laravel 8 - PHP 8
  # =================

  Laravel8-PHP8:
    needs: PHP8-Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel/8/php8
          build_tags: |
            ggmartinez/laravel:8-php8
            ggmartinez/laravel:8
  Laravel8-PHP8-Xdebug:
    needs: Laravel8-PHP8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel/8/php8-xdebug
          build_tags: |
            ggmartinez/laravel:8-php8-Xdebug
            ggmartinez/laravel:8-Xdebug

  Laravel8-PHP8-MSSQL:
    needs: Laravel8-PHP8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel/8/php8-mssql
          build_tags: |
            ggmartinez/laravel:8-php8-mssql
            ggmartinez/laravel:8-mssql

  Laravel8-PHP8-MSSQL-Xdebug:
    needs: Laravel8-PHP8-Xdebug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./PHP/Laravel/8/php8-mssql-xdebug
          build_tags: |
            ggmartinez/laravel:8-php8-mssql-xdebug
            ggmartinez/laravel:8-mssql-xdebug

  # =================
  # Python 
  # =================

  Python2-Debugpy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Python/2/Debugpy
          build_tags: |
            ggmartinez/python:2-debugpy
  Python3-Debugpy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Python/3/Debugpy
          build_tags: |
            ggmartinez/python:3-debugpy
  Django-165:
    runs-on: ubuntu-latest
    needs: Python2-Debugpy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_context: ./Python/Django/1.6.5
          build_tags: |
            ggmartinez/django:1.6.5


