name: 'PHP 8'

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_username: ${{ secerts.DOCKERHUB_USER }}
          dockerhub_password: ${{ secerts.DOCKERHUB_PASSWORD }}
          build_context: ./PHP8/Base
          build_tags: |
            ggmartinez/php:8
            ggmartinez/php:latest
  Apache:
    runs-on: ubuntu-latest
    needs: Base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/docker-build
        with:
          dockerhub_username: ${{ secerts.DOCKERHUB_USER }}
          dockerhub_password: ${{ secerts.DOCKERHUB_PASSWORD }}
          build_context: ./PHP8/Apache
          build_tags: |
            ggmartinez/php:8-apache
            ggmartinez/php:latest-apache
